### ISSUE TITLE
Run DBT on Google Cloud Composer: Issue Permission Denied

### ISSUE THREAD

**Issue by tvlk-karl** [gocardless/airflow-dbt#21]
Hi Gocardless team,
thanks for this amazing package, truly great of combined airflow and dbt as well

I have an issue, I'm running airflow-dbt within cloud composer, and got this error
> ERROR - [Errno 13] Permission denied: '/home/airflow/gcs/dags/dbt_cx'

Can you guys help on this?
Thanks again

**Comment by tvlk-karl** [comment]
@gocardless-robot @gocardless-robot-admin @LizGoCardless

**Comment by andrewrjones** [comment]
Hey @tvlk-karl,

We don't use Cloud Composer so I don't know too much about it.

Is `dbt_cx` the name of the `dbt` CLI? If so, it could be that you need to set the _executable_ permission on it, e.g. `chmod +x dbt_cx`.

Or is this is the directory containing your DAG, then it's likely whatever user Cloud Composer is running as does not have permission to read that directory.

Hope this helps!

**Comment by andrewrjones** [comment]
Closing as stale.
