### ISSUE TITLE
Release a version with DbtDocsGenerateOperator included

### ISSUE THREAD

**Issue by chuhsuanlee** [gocardless/airflow-dbt#38]
Hi I saw there's a merged PR (#28) regarding to DbtDocsGenerateOperator, but it's not avaiable in the latest pip version yet. I know it's been a while, but just curious if it's possible to have a new version release with DbtDocsGenerateOperator included?

**Comment by kkwan-tc** [comment]
We would also like to get a new release 🙏

**Comment by andrewrjones** [comment]
Sorry for the delay, this is now done! https://pypi.org/project/airflow-dbt/0.4.0/
