### ISSUE TITLE
Make vars templated_fields

### ISSUE THREAD

**Issue by tomsej** [gocardless/airflow-dbt#7]
Hi thanks for this repo. Could you please make a `vars` a templated field? https://airflow.apache.org/docs/stable/concepts.html#jinja-templating

**Comment by andrewrjones** [comment]
Hi @tomsej,

Thanks for the suggestion. We can certainly do this, and it would make a lot of sense. We'll try to get to this in the next day or two!

Thanks,
Andrew

**Comment by ee07dazn** [comment]
Hi Guys, thanks for this repo. Any update on the issue? I am keen to use {{ ds }} from airflow into a query in one of my models in dbt. And i believe the resolution to this issue will solve my problem.

**Comment by TimmyCarbone** [comment]
+1 for this!

Thank you for addressing it!

Is the commit above enough to fix this issue or is the resolution still ongoing?
If it is, I guess we can pull the branch instead of the latest release.

Thanks!
